spring.application.name=beuu2s3g2ex
spring.config.import=file:env.properties
#SERVER CONFIG
server.port=${PORT}
#SPRING
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
#HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${JWT_SECRET}